# Generated by Django 4.0.3 on 2022-03-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calorie_count',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
