# Generated by Django 4.0.3 on 2022-03-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_profile_calorie_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='food_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calories.fooditems'),
        ),
    ]
