# Generated by Django 4.0.3 on 2022-03-21 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0003_alter_profile_food_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='total_calories',
            new_name='total_calorie',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('calorie', models.FloatField(default=0)),
                ('person_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='postfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories.food'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='all_food_selected_today',
            field=models.ManyToManyField(related_name='inventory', through='calories.PostFood', to='calories.food'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='food_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calories.food'),
        ),
        migrations.DeleteModel(
            name='FoodItems',
        ),
    ]
