# Generated by Django 4.0.3 on 2022-03-21 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0004_rename_total_calories_profile_total_calorie_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='all_food_selected_today',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='food_selected',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='person_of',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='calorie',
            new_name='carbs',
        ),
        migrations.RemoveField(
            model_name='food',
            name='person_of',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PostFood',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='consume',
            name='food_consumed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories.food'),
        ),
        migrations.AddField(
            model_name='consume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
